### ISSUE TITLE
Reflexive Relationships Not Handled Correctly For Concrete Superclasses

### ISSUE THREAD

**Issue by cfi-dphillips** [emfjson/ecore.js#10]
While doing a load of an XMI instance file that conforms to an XMI ecore, when the class has a reflexive relationship, is not abstract, and there are subclasses:

1. The Ecore.XMI.parse getClassURIFromFeatureType function fails to detect the subclasses and treats them as if they are the superclass.
2. When this situation is resolved, the Ecore.XMI.to function fails to insert the xsi:type attributes for the subclasses when emitting XMI from the loaded model instance.

We have identified a potential fix for consideration and will submit a pull request after we finish updating the test cases and check for any other side effects.

**Comment by cfi-dphillips** [comment]
Changes and tests for these two situations have been merged into our forked repo at:
https://github.com/CohesionForce/ecore.js

We believe we have found an additional related issue when the reflexive relation is by reference instead of by composition.

**Comment by cfi-dphillips** [comment]
We added a xmi.test.js test case that it "should parse instances of test5 correctly" to the above repo in addition to the changes to fix the problem.  Accept the changes to xmi.test.js and the ./test/models/test5* files to reproduce the problem.

**Comment by ghillairet** [comment]
Thanks for reporting this, I will look at it.
