### ISSUE TITLE
Missing Some Standard XMI Attributes

### ISSUE THREAD

**Issue by cfi-dphillips** [emfjson/ecore.js#18]
The parser skips a few attributes that seem to be used in many EMF xmi files such as "xmi:id" and "href".  Do you have any suggestions on how to get this loaded for instance of models?

**Comment by cfi-dphillips** [comment]
We uploaded a commit that has the tests that we think should pass (dee4b116d48796b3a152043351e39cd1fc225d89). The tests are currently selected to be skipped and will need to be edited to demonstrate the problem.

**Comment by ghillairet** [comment]
This has been fixed in version 0.8.0
