### ISSUE TITLE
Questions, project relations

### ISSUE THREAD

**Issue by magick93** [emfjson/ecore.js#25]
Hello

Does EmfJson have any relationship to http://som-research.uoc.edu/tools/emf-rest/ ? Or are these two separate projects that are trying to achieve a similar thing?

Does EmfJson generate javascript classes from an ecore model?

Thanks

**Comment by ghillairet** [comment]
This project, ecorejs has no relations with emf-rest. It's an implementation of the Ecore model and subset of the EMF API in Javascript. It doesn't support code generation, it is mostly similar to the dynamic API available in EMF. It can load ecore models from XMI or JSON, and provides an API to manipulate them in the browser or server side (e.g. in nodejs apps).
