### ISSUE TITLE
TypeError: resourceSet.fetch is not a function

### ISSUE THREAD

**Issue by vsimko** [emfjson/ecore.js#36]
I'm using `"ecore": "^0.11.0"`

The Example from http://emfjson.org/ecore.js/#resources does not work:
```js
var Ecore = require('ecore');
var resourceSet = Ecore.ResourceSet.create();
resourceSet.fetch();
```

Error:
```
resourceSet.fetch();
            ^
TypeError: resourceSet.fetch is not a function
   ... stack trace
```

**Comment by ghillairet** [comment]
I will need to update the docs, this function has been removed. You should use the `resource.load` function. This function takes for parameter a string being the JSON or XMI data, and a callback function.
The reason for having fetch removed is that I didn't want to keep a dependency on jQuery, which was present before and was making the http call to retrieve data for a potential server. You would have to handle this yourself. have your app make the http call that returns a JSON string and pass it to the `resource.load` function to fill the resource with content.
