### ISSUE TITLE
How to associate EObjects with a package

### ISSUE THREAD

**Issue by magick93** [emfjson/ecore.js#44]
Hi

The documentation on http://emfjson.org/ecore.js/ is really useful.

However, unless I am overlooking something, it shows how to create a package, and how to create various EObjects - but not how to add the EObjects to a package. 
Eg, how does one add the Library object to the LibraryPackage?

Can someone please describe how to do this?

Thanks

**Comment by ghillairet** [comment]
Look here https://github.com/emfjson/ecore.js/blob/master/test/resource.test.js#L17 you can see how to do that by invoking an API similar to the Java one.
